spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dt_finance?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: flms04
  data:
    redis:
      url: 192.168.39.233
      port: 16379
      database: 1
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 5000

